### ISSUE TITLE
Setting to warn if using assign (=) instead of expression (:=)

### ISSUE THREAD

**Issue by B0sh** [yedhrab/YAutoHotkey-VSCode#2]
Hey, I love to see a new ahk extension on vs code. I've tried all of them, but nobody has a feature that I'm really looking for. I want something that highlights a line that uses equals to assign a variable instead of colon equals, since I've had many issues where I had bugs related to forgetting the colon and expecting it to use expression syntax. The "warning" could be anything as long as it is noticeable. I'm not sure what options are available to extensions. To be clear, this is what I'm looking for:

```
Warned Line:
Message = "Errors and warnings"

Allowed Line:
Message := "Errors and warnings"
```

It'd probably be good to have this be a feature that defaults to off since I'm pretty sure most people don't care/like to use equals.

Thanks, 
B0sh

**Comment by yemreak** [comment]
Can the different coloration of the assignment and equality operator help you instead of the warning message?

![image](https://user-images.githubusercontent.com/49655146/71381312-00897100-25e4-11ea-9995-0d4c540d1e3d.png)

**Comment by yemreak** [comment]
👨‍🔧 Resolved in new version

> You need to install [🖤 DarkCode Theme](https://marketplace.visualstudio.com/items?itemName=yedhrab.darkcode-theme-adopted-python-and-markdown) extension (that support this colorization) to use this feature.
